# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ak1h2W6vLNQDbPbO9usLlcr8Yb2Gq29h
"""

N = input()
N_1 = [int(x) for x in N]
size = input().split(' ')
inventory = [str(x) for x in size]
request = input()
request_no = [int(x) for x in request]
req_size = input().split(' ')
request = [str(x) for x in req_size]

for total in request:
  if int(N) >= int(request):
    if inventory == total:
       print("Yes")

  else:
    print('No')